[tool.poetry]
name = "scraper"
version = "0.1.0"
description = ""
authors = ["Andrii"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.41.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
